
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy

  export const environment = {
    production: false,
    HARPER_DB_HOST: 'localhost',
    HARPER_DB_USERNAME: 'undefined',
    HARPER_DB_PASSWORD: 'undefined',
    firebaseConfig: {}
  };
