
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy

  export const environment = {
    production: false,
    HARPER_DB_HOST: 'https://cloud-1-expensetracker.harperdbcloud.com',
    HARPER_DB_USERNAME: 'yuvaraj',
    HARPER_DB_PASSWORD: '7O3&qYPniXt',
    firebaseConfig: {       apiKey: "AIzaSyAqt6VMMywx07ycv7KuTr1ykUhFxsRvGKo",       authDomain: "qa-quiz-fe69f.firebaseapp.com",       projectId: "qa-quiz-fe69f",       storageBucket: "qa-quiz-fe69f.appspot.com",       messagingSenderId: "1032775171001",       appId: "1:1032775171001:web:727a69cfdb85d867281468",       measurementId: "G-0324Y4ZYWF"     }
  };
